### ISSUE TITLE
Figure out how to use the packet captures

### ISSUE THREAD

**Issue by ghost** [wilkening-mark/NortheasternCTF2016#9]
We should figure out how to use the packet captures to try a replay attack.

**Comment by Young-dwarflemur** [comment]
we could just make a janky server and redirect the the stuff there with socat instead of to the mitre server and then make a fake widget to send them

**Comment by samgray** [comment]
what do you open the packet capture files with ?

**Comment by Young-dwarflemur** [comment]
Didn't we talk about that yesterday? You just open them with wireshark
